package rokuniroku.code.newintiiu;

import java.io.Serializable;

public class INTIAnn implements Serializable{

    private String title;
    private String venue; // MPH
    private String category; // FITS, OAR
    private String dateUpload; // 09/07/2018
    private String timeUpload; // 11:30, 23:30
    private String deleteDate; // specified by poser or +1 day to the date occurrence
    private String content; // long contents
    private String banner; // set the unique key, to point to the same location in the storage, the key is generated by the push function
    private String dateStart;
    private String dateEnd;
    private String timeStart;
    private String timeEnd;

    public INTIAnn(){

    }

    public INTIAnn(String title, String venue, String category, String dateUpload, String timeUpload, String deleteDate, String content, String banner, String dateStart, String dateEnd, String timeStart, String timeEnd) {
        this.title = title;
        this.venue = venue;
        this.category = category;
        this.dateUpload = dateUpload;
        this.timeUpload = timeUpload;
        this.deleteDate = deleteDate;
        this.content = content;
        this.banner = banner;
        this.dateStart = dateStart;
        this.dateEnd = dateEnd;
        this.timeStart = timeStart;
        this.timeEnd = timeEnd;
    }

    public String getTitle() {
        return title;
    }

    public String getVenue() {
        return venue;
    }

    public String getCategory() {
        return category;
    }

    public String getDateUpload() {
        return dateUpload;
    }

    public String getTimeUpload() {
        return timeUpload;
    }

    public String getDeleteDate() {
        return deleteDate;
    }

    public String getContent() {
        return content;
    }

    public String getBanner() {
        return banner;
    }

    public String getDateStart() {
        return dateStart;
    }

    public String getDateEnd() {
        return dateEnd;
    }

    public String getTimeStart() {
        return timeStart;
    }

    public String getTimeEnd() {
        return timeEnd;
    }
}
