package rokuniroku.code.intiiu;

import java.io.Serializable;

public class INTIAnn implements Serializable{

    private String title;
    private String category; // FITS, OAR
    private String dateUpload; // 09/07/2018
    private String timeUpload; // 11:30, 23:30
    private String courtDate; // specified by poser or +1 day to the date occurrence
    private String content; // long contents
    private String banner; // set the unique key, to point to the same location in the storage, the key is generated by the push function
    private String dateOccur; // 27/07/2018 - 27/07/2018
    private String timeOccur; // start time of the first day - end time of the last day, 17:30 - 20:00

    public INTIAnn(){

    }

    public INTIAnn(String title, String category, String dateUpload, String timeUpload, String courtDate, String content, String banner, String dateOccur, String timeOccur) {
        this.title = title;
        this.category = category;
        this.dateUpload = dateUpload;
        this.timeUpload = timeUpload;
        this.courtDate = courtDate;
        this.content = content;
        this.banner = banner;
        this.dateOccur = dateOccur;
        this.timeOccur = timeOccur;
    }

    public String getTitle() {
        return title;
    }

    public String getCategory() {
        return category;
    }

    public String getDateUpload() {
        return dateUpload;
    }

    public String getTimeUpload() {
        return timeUpload;
    }

    public String getCourtDate() {
        return courtDate;
    }

    public String getContent() {
        return content;
    }

    public String getBanner() {
        return banner;
    }

    public String getDateOccur() {
        return dateOccur;
    }

    public String getTimeOccur() {
        return timeOccur;
    }
}
